### PR TITLE
TOC File changes and Updates to Toolbar

### PR DESCRIPTION
**Pull request by Starlynk1**
Renamed TOC and added Vanilla TOC
Updated Toolbar.lua to include check for WOW_PROJECT_ID
Toolbar will show 6 slots for Classic Era and 7 slots for Wrath

### CODE REVIEW

**Comment by Starlynk1** [comment]
Tested in Wrath and Classic Era, no errors
Last commit was to get TOCs to current game versions

**Comment by Wuild** [comment]
Thank you for all of these updates... I am however working on a 2.0 version at the moment and i wont push an update at this point

**Comment by Starlynk1** [comment]
Ah cool, really look forward to seeing it. And hoping it isn't as convoluted with code like Fishing Buddy is now due to the various game versions. But honestly, after like 17 years I can see why it got so bloated. I used to do minor bug help with Sutorix on that one and was so happy when I found FishMaster and a more lightweight fishing addon.

If you need/want anyone to test for Classic Era (I am currently focued on hardcore), I will gladly help and provide feedback.

Thanks!
________________________________

**Comment by Wuild** [comment]
I developed this on the launch of classic, and i have not really touched it since. So i am doing a full rework of everything :)
Currently doing HC (Stiches) aswell!

**Comment by Wuild** [comment]
https://github.com/Wuild/FishMaster/tree/2.0
If you want to test it out and or fix some of the bugs
Please & Thank you

**Comment by Starlynk1** [comment]
I was checking out the 2.0 but its not working. Looking at the files, it looks like there are some missing modules and scripts its trying to call. Are those on your local drive and not uploaded yet?

**Comment by Wuild** [comment]
weird... been disabling all other addons when developing it havent had any issues.. you got any logs on what scripts its missing? guessing github has messed somthing up

**Comment by Starlynk1** [comment]
This is the error on a new toon without fishing skills yet
```
34x FishMaster/modules/toolbar.lua:59: attempt to index local 'lure' (a nil value)
[string "@FishMaster/modules/toolbar.lua"]:59: in function `UpdateCastButton'
[string "@FishMaster/modules/toolbar.lua"]:193: in function `?'
[string "@BagBrother/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:119: in function <...her/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@BagBrother/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:29: in function <...her/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:25>
[string "@BagBrother/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:64: in function `Fire'
[string "@BagBrother/libs/AceEvent-3.0-4/AceEvent-3.0.lua"]:120: in function <BagBrother/libs/AceEvent-3.0/AceEvent-3.0.lua:119>

Locals:
self = <table> {
 SetDefaultModuleLibraries = <function> defined @Bartender4/libs/AceAddon-3.0/AceAddon-3.0.lua:363
 CreateLureButtons = <function> defined @FishMaster/modules/toolbar.lua:75
 Enable = <function> defined @Bartender4/libs/AceAddon-3.0/AceAddon-3.0.lua:290
 UnregisterAllEvents = <function> defined @BagBrother/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:174
 EnableModule = <function> defined @Bartender4/libs/AceAddon-3.0/AceAddon-3.0.lua:328
 modules = <table> {
 }
 GetModule = <function> defined @Bartender4/libs/AceAddon-3.0/AceAddon-3.0.lua:206
 IterateEmbeds = <function> defined @Bartender4/libs/AceAddon-3.0/AceAddon-3.0.lua:438
 defaultModuleLibraries = <table> {
 }
 CheckForDoubleClick = <function> defined @FishMaster/modules/toolbar.lua:196
 ResetOverride = <function> defined @FishMaster/modules/toolbar.lua:237
 SetDefaultModulePrototype = <function> defined @Bartender4/libs/AceAddon-3.0/AceAddon-3.0.lua:405
 CreateCastButton = <function> defined @FishMaster/modules/toolbar.lua:42
 name = "FishMaster_Modules_Toolbar"
 IsEnabled = <function> defined @Bartender4/libs/AceAddon-3.0/AceAddon-3.0.lua:447
 orderedModules = <table> {
 }
 SetOverride = <function> defined @FishMaster/modules/toolbar.lua:229
 DisableModule = <function> defined @Bartender4/libs/AceAddon-3.0/AceAddon-3.0.lua:346
 RegisterMessage = <function> defined @BagBrother/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:90
 UnregisterMessage = <function> defined @BagBrother/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:153
 baseName = "FishMaster"
 defaultModuleState = true
 IsModule = <function> defined @Bartender4/libs/AceAddon-3.0/AceAddon-3.0.lua:213
 OnMouseDown = <function> defined @FishMaster/modules/toolbar.lua:212
 SetDefaultModuleState = <function> defined @Bartender4/libs/AceAddon-3.0/AceAddon-3.0.lua:383
 OnDisable = <function> defined @FishMaster/modules/toolbar.lua:173
 OnEnable = <function> defined @FishMaster/modules/toolbar.lua:161
 SetEnabledState = <function> defined @Bartender4/libs/AceAddon-3.0/AceAddon-3.0.lua:420
 OnInitialize = <function> defined @FishMaster/modules/toolbar.lua:148
 enabledState = false
 UpdateLureButtons = <function> defined @FishMaster/modules/toolbar.lua:118
 RegisterEvent = <function> defined @BagBrother/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:90
 UnregisterAllMessages = <function> defined @BagBrother/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:174
 EventHandler = <function> defined @FishMaster/modules/toolbar.lua:182
 UpdateCastButton = <function> defined @FishMaster/modules/toolbar.lua:53
 CreateFrame = <function> defined @FishMaster/modules/toolbar.lua:15
 IterateModules = <function> defined @Bartender4/libs/AceAddon-3.0/AceAddon-3.0.lua:433
 NewModule = <function> defined @Bartender4/libs/AceAddon-3.0/AceAddon-3.0.lua:231
 GetName = <function> defined @Bartender4/libs/AceAddon-3.0/AceAddon-3.0.lua:275
 SendMessage = <function> defined @BagBrother/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:59
 moduleName = "Toolbar"
 UnregisterEvent = <function> defined @BagBrother/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:153
 Disable = <function> defined @Bartender4/libs/AceAddon-3.0/AceAddon-3.0.lua:310
}
frame = FishMaster_ToolbarCast {
 0 = <userdata>
 icon = FishMaster_ToolbarCastIconTexture {
 }
 count = FontString {
 }
}
lured = false
lure = nil
text = ""
(*temporary) = ""
(*temporary) = "/use "
(*temporary) = <function> defined =[C]:-1
(*temporary) = nil
(*temporary) = "attempt to ind
```

I had different errors on toons that had fishing skills. I will grab fishing shortly and get that other error

**Comment by Starlynk1** [comment]
Just got fishing skill and now both windows are showing. Maybe something with your update a few hours ago got those missing items to show up.  Only error I am getting now is the following. But that is probably due to the equipment manager screen not being ready yet.

```
8x FishMaster/FishMaster.lua:84: attempt to index field 'equipment' (a nil value)
[string "@FishMaster/FishMaster.lua"]:84: in function `OnClick'
[string "@Bartender4/libs/LibDBIcon-1.0-52/LibDBIcon-1.0.lua"]:170: in function <...dOns/Bartender4/libs/LibDBIcon-1.0/LibDBIcon-1.0.lua:168>

Locals:
self = LibDBIcon10_FishMasterMinimapIcon {
 0 = <userdata>
 fadeOut = AnimationGroup {
 }
 dataObject = <table> {
 }
 isMouseDown = false
 db = <table> {
 }
 sexyMapFadeOut = AnimationGroup {
 }
 icon = Texture {
 }
}
button = "RightButton"
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'equipment' (a nil value)"
```

**Comment by Starlynk1** [comment]
@Wuild Not able to create pull request for the 2.0 branch. Have minor update that would like to send over.

**Pull request closed without merging**
